### ISSUE TITLE
Migrate from tfenv to tenv

### ISSUE THREAD

**Issue by kvendingoldo** [Arrow-air/tools#46]
Hi! I saw that you're using tfenv in this repository. It's a really good tool, but it does not support OpenTofu and Terragrunt. My team designed a successor of tenv that support Terraform, Terragrunt and OpenTofu. It will be a good idea to migrate into it in due to the growing popularity of OpenTofu.
url: https://github.com/tofuutils/tenv

**Comment by amsmith-pro** [comment]
Thanks @kvendingoldo! We'll evaluate this option soon. It's a busy week for us so maybe in a couple weeks time

**Comment by owlot** [comment]
Oh, I never saw this issue, but we've actually added tenv in May so this issue can be closed:
https://github.com/Arrow-air/tools/tree/main/docker/arrow-tenv
